
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://subversive.herokuapp.com/v2/entry/subversive-eu/site/master/comments

