name: Build GH-Pages

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'netlify.toml'
      - '/public/'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --gc --verbose --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.BUILD_HUGO }}
          publish_dir: ./public
          cname: subversive.eu